### ISSUE TITLE
Transifex / react-intl "Error validating message" blocking pull translations

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#1547]
**Description**
> 15:38:45 [@formatjs/cli] [WARN] Error validating message "نوع {count، plural, one {الملف} other {الملفات}} المقبول هو {typeString}." with ID "dropzone.Dropzone.invalidType" in file "./src/i18n/messages/ar.json"
> 15:38:45 SyntaxError: MALFORMED_ARGUMENT

It appears there may be a newly reviewed translation for the `ar` locale regarding the `dropzone.Dropzone.invalidType` message extracted from `Dropzone`. Let's look into the error and see if we can resolve to get the `pull_translations` job working again.

Reach out to @adamstankiewicz (preferably on Slack) to re-run the Transifex `pull_translations` job as needed.

**Full stack trace**
```
15:38:00 Started by timer
15:38:00 [EnvInject] - Loading node environment variables.
15:38:00 [EnvInject] - Preparing an environment for the build.
15:38:00 [EnvInject] - Keeping Jenkins system variables.
15:38:00 [EnvInject] - Keeping Jenkins build variables.
15:38:00 [EnvInject] - Injecting as environment variables the properties content 
15:38:00 REPO_NAME=paragon
15:38:00 SETUP_SCRIPT=nodeenv -p --node=16.15.0 --prebuilt --force
15:38:00 JOB_SCRIPT=python3.8 transifex/pull.py https://github.com/edx/paragon.git openedx/paragon --skip-compilemessages
15:38:00 GIT_USER_NAME=edX Transifex Bot
15:38:00 GIT_USER_EMAIL=learner-engineering@edx.org
15:38:00 REQUIREMENT_FILE=transifex/requirements/microfrontend-common.txt
15:38:00 LMS_CFG=
15:38:00 STUDIO_CFG=
15:38:00 REVISION_CFG=
15:38:00 
15:38:00 [EnvInject] - Variables injected successfully.
15:38:00 [EnvInject] - Injecting contributions.
15:38:00 Building in workspace /edx/var/jenkins/jobs/translations/jobs/paragon-pull_translations/workspace
15:38:00  > git rev-parse --is-inside-work-tree # timeout=10
15:38:00 Fetching changes from the remote Git repository
15:38:00  > git config remote.origin.url https://github.com/edx/ecommerce-scripts.git # timeout=10
15:38:00 Pruning obsolete local branches
15:38:00 Fetching upstream changes from https://github.com/edx/ecommerce-scripts.git
15:38:00  > git --version # timeout=10
15:38:00  > git -c core.askpass=true fetch --tags --progress https://github.com/edx/ecommerce-scripts.git +refs/heads/*:refs/remotes/origin/* --prune
15:38:00  > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
15:38:00  > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
15:38:00 Checking out Revision 563b4d6d9185961412d1b20ee1d5c5348e4ba361 (refs/remotes/origin/master)
15:38:00  > git config core.sparsecheckout # timeout=10
15:38:00  > git checkout -f 563b4d6d9185961412d1b20ee1d5c5348e4ba361
15:38:00  > git rev-list 563b4d6d9185961412d1b20ee1d5c5348e4ba361 # timeout=10
15:38:00 Cleaning workspace
15:38:00  > git rev-parse --verify HEAD # timeout=10
15:38:00 Resetting working tree
15:38:00  > git reset --hard # timeout=10
15:38:00  > git clean -fdx # timeout=10
15:38:00 [workspace] $ /bin/bash -xe /tmp/hudson7730427594334758294.sh
15:38:00 + set +u
15:38:00 + . /edx/var/jenkins/jobvenvs/virtualenv_tools.sh
15:38:00 + create_virtualenv --python=python3.8 --clear
15:38:00 + '[' -z '' ']'
15:38:00 + echo 'No JOBVENVDIR found. Using default value.'
15:38:00 No JOBVENVDIR found. Using default value.
15:38:00 + JOBVENVDIR=/edx/var/jenkins/jobvenvs
15:38:00 ++ pwd
15:38:00 + echo 'Creating venv for /edx/var/jenkins/jobs/translations/jobs/paragon-pull_translations/workspace'
15:38:00 Creating venv for /edx/var/jenkins/jobs/translations/jobs/paragon-pull_translations/workspace
15:38:00 ++ pwd
15:38:00 ++ md5sum
15:38:00 ++ cut '-d ' -f1
15:38:00 + venvname=c1c36453ca7cea9f9a09f2f04c106e3b
15:38:00 + virtualenv --python=python3.8 --clear /edx/var/jenkins/jobvenvs/c1c36453ca7cea9f9a09f2f04c106e3b
15:38:04 created virtual environment CPython3.8.14.final.0-64 in 3966ms
15:38:04   creator CPython3Posix(dest=/edx/var/jenkins/jobvenvs/c1c36453ca7cea9f9a09f2f04c106e3b, clear=True, no_vcs_ignore=False, global=False)
15:38:04   seeder FromAppData(download=False, pip=bundle, wheel=bundle, setuptools=bundle, via=copy, app_data_dir=/edx/var/jenkins/.local/share/virtualenv)
15:38:04     added seed packages: pip==22.3.1, setuptools==65.6.3, wheel==0.38.4
15:38:04   activators PythonActivator,FishActivator,XonshActivator,CShellActivator,PowerShellActivator,BashActivator
15:38:04 + venvpath=/edx/var/jenkins/jobvenvs/c1c36453ca7cea9f9a09f2f04c106e3b
15:38:04 + . /edx/var/jenkins/jobvenvs/c1c36453ca7cea9f9a09f2f04c106e3b/bin/activate
15:38:04 ++ '[' /edx/var/jenkins/jobvenvs/c1c36453ca7cea9f9a09f2f04c106e3b/bin/activate = /tmp/hudson7730427594334758294.sh ']'
15:38:04 ++ deactivate nondestructive
15:38:04 ++ unset -f pydoc
15:38:04 ++ '[' -z '' ']'
15:38:04 ++ '[' -z '' ']'
15:38:04 ++ '[' -n /bin/bash ']'
15:38:04 ++ hash -r
15:38:04 ++ '[' -z '' ']'
15:38:04 ++ unset VIRTUAL_ENV
15:38:04 ++ '[' '!' nondestructive = nondestructive ']'
15:38:04 ++ VIRTUAL_ENV=/edx/var/jenkins/jobvenvs/c1c36453ca7cea9f9a09f2f04c106e3b
15:38:04 ++ '[' linux-gnu = cygwin ']'
15:38:04 ++ '[' linux-gnu = msys ']'
15:38:04 ++ export VIRTUAL_ENV
15:38:04 ++ _OLD_VIRTUAL_PATH=/usr/lib/jvm/java-8-oracle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
15:38:04 ++ PATH=/edx/var/jenkins/jobvenvs/c1c36453ca7cea9f9a09f2f04c106e3b/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
15:38:04 ++ export PATH
15:38:04 ++ '[' -z '' ']'
15:38:04 ++ '[' -z '' ']'
15:38:04 ++ _OLD_VIRTUAL_PS1=
15:38:04 ++ '[' x '!=' x ']'
15:38:04 +++ basename /edx/var/jenkins/jobvenvs/c1c36453ca7cea9f9a09f2f04c106e3b
15:38:04 ++ PS1='(c1c36453ca7cea9f9a09f2f04c106e3b) '
15:38:04 ++ export PS1
15:38:04 ++ alias pydoc
15:38:04 ++ true
15:38:04 ++ '[' -n /bin/bash ']'
15:38:04 ++ hash -r
15:38:04 + set -u
15:38:04 + echo '[https://www.transifex.com/]'
15:38:04 + echo 'hostname = https://www.transifex.com/'
15:38:04 + echo 'username = ****'
15:38:04 + echo 'password = ****'
15:38:04 + echo 'rest_hostname = https://rest.api.transifex.com/'
15:38:04 + echo 'token = ********'
15:38:04 + cd ecommerce-scripts
15:38:04 + pip3 install -r transifex/requirements/microfrontend-common.txt
15:38:05 Collecting Django==2.2.20
15:38:05   Using cached Django-2.2.20-py3-none-any.whl (7.5 MB)
15:38:06 Collecting edx-i18n-tools==0.5.3
15:38:06   Using cached edx_i18n_tools-0.5.3-py2.py3-none-any.whl (29 kB)
15:38:06 Collecting PyGithub==1.55
15:38:06   Using cached PyGithub-1.55-py3-none-any.whl (291 kB)
15:38:06 Collecting PyYAML==5.4
15:38:06   Using cached PyYAML-5.4-cp38-cp38-manylinux1_x86_64.whl (662 kB)
15:38:06 Collecting nodeenv==1.3.0
15:38:06   Using cached nodeenv-1.3.0-py3-none-any.whl
15:38:06 Collecting pytz
15:38:06   Using cached pytz-2022.7-py2.py3-none-any.whl (499 kB)
15:38:06 Collecting sqlparse>=0.2.2
15:38:06   Using cached sqlparse-0.4.3-py3-none-any.whl (42 kB)
15:38:06 Collecting path.py>=7.0
15:38:06   Using cached path.py-12.5.0-py3-none-any.whl (2.3 kB)
15:38:06 Collecting six
15:38:06   Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
15:38:06 Collecting polib
15:38:06   Using cached polib-1.1.1-py2.py3-none-any.whl (20 kB)
15:38:06 Collecting requests>=2.14.0
15:38:06   Using cached requests-2.28.1-py3-none-any.whl (62 kB)
15:38:06 Collecting pynacl>=1.4.0
15:38:06   Using cached PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
15:38:06 Collecting deprecated
15:38:06   Using cached Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
15:38:06 Collecting pyjwt>=2.0
15:38:06   Using cached PyJWT-2.6.0-py3-none-any.whl (20 kB)
15:38:06 Collecting path
15:38:06   Using cached path-16.6.0-py3-none-any.whl (26 kB)
15:38:06 Collecting cffi>=1.4.1
15:38:06   Using cached cffi-1.15.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (442 kB)
15:38:06 Collecting idna<4,>=2.5
15:38:06   Using cached idna-3.4-py3-none-any.whl (61 kB)
15:38:07 Collecting charset-normalizer<3,>=2
15:38:07   Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
15:38:07 Collecting urllib3<1.27,>=1.21.1
15:38:07   Using cached urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
15:38:07 Collecting certifi>=2017.4.17
15:38:07   Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
15:38:07 Collecting wrapt<2,>=1.10
15:38:07   Using cached wrapt-1.14.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (81 kB)
15:38:07 Collecting pycparser
15:38:07   Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
15:38:07 Installing collected packages: pytz, polib, nodeenv, wrapt, urllib3, sqlparse, six, PyYAML, pyjwt, pycparser, path, idna, charset-normalizer, certifi, requests, path.py, Django, deprecated, cffi, pynacl, edx-i18n-tools, PyGithub
15:38:10 Successfully installed Django-2.2.20 PyGithub-1.55 PyYAML-5.4 certifi-2022.12.7 cffi-1.15.1 charset-normalizer-2.1.1 deprecated-1.2.13 edx-i18n-tools-0.5.3 idna-3.4 nodeenv-1.3.0 path-16.6.0 path.py-12.5.0 polib-1.1.1 pycparser-2.21 pyjwt-2.6.0 pynacl-1.5.0 pytz-2022.7 requests-2.28.1 six-1.16.0 sqlparse-0.4.3 urllib3-1.24.3 wrapt-1.14.1
15:38:10 + mkdir transifex_client
15:38:10 + cd transifex_client
15:38:10 + curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh
15:38:10 + bash
15:38:10   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
15:38:10                                  Dload  Upload   Total   Spent    Left  Speed
15:38:10 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3426  100  3426    0     0   196k      0 --:--:-- --:--:-- --:--:--  196k
15:38:10 ** Installing CLI from https://github.com/transifex/cli/releases/latest/download/tx-linux-amd64.tar.gz
15:38:10 
15:38:10   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
15:38:10                                  Dload  Upload   Total   Spent    Left  Speed
15:38:10 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
15:38:10 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
15:38:10 
100 4165k  100 4165k    0     0  14.7M      0 --:--:-- --:--:-- --:--:-- 14.7M
15:38:10 
15:38:10 ** Adding CLI to PATH
15:38:10 ** Profile not found, we tried for .profile, .bashrc, .bash_profile, .zshrc
15:38:10 ** Please add this line to the correct file if you want to access 'tx' from any path.
15:38:10 
15:38:10 export PATH="/edx/var/jenkins/jobs/translations/jobs/paragon-pull_translations/workspace/ecommerce-scripts/transifex_client:$PATH"
15:38:10 
15:38:10 
15:38:10 ** If everything went fine you should see the Transifex CLI version in the following line.
15:38:10 TX Client, version=1.6.4
15:38:10 + export PATH=/edx/var/jenkins/jobs/translations/jobs/paragon-pull_translations/workspace/ecommerce-scripts/transifex_client:/edx/var/jenkins/jobvenvs/c1c36453ca7cea9f9a09f2f04c106e3b/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
15:38:10 + PATH=/edx/var/jenkins/jobs/translations/jobs/paragon-pull_translations/workspace/ecommerce-scripts/transifex_client:/edx/var/jenkins/jobvenvs/c1c36453ca7cea9f9a09f2f04c106e3b/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
15:38:10 + cd ..
15:38:10 + set +u
15:38:10 + nodeenv -p --node=16.15.0 --prebuilt --force
15:38:12  * Install prebuilt node (16.15.0) ..... done.
15:38:12  * Appending data to /edx/var/jenkins/jobvenvs/c1c36453ca7cea9f9a09f2f04c106e3b/bin/activate
15:38:12  * Appending data to /edx/var/jenkins/jobvenvs/c1c36453ca7cea9f9a09f2f04c106e3b/bin/activate.fish
15:38:12 + set -u
15:38:12 + python3.8 transifex/pull.py https://github.com/edx/paragon.git openedx/paragon --skip-compilemessages
15:38:13 Cloning into 'configuration'...
15:38:14 Switched to a new branch 'transifex-bot-update-translations2023-01-01'
15:38:14 2023-01-01 20:38:14,051 INFO 25860 [pull.py:54] - Pulling lms/studio settings from [configuration].
15:38:14 Cloning into 'paragon'...
15:38:15 Switched to a new branch 'transifex-bot-update-translations2023-01-01'
15:38:15 2023-01-01 20:38:15,550 INFO 25860 [pull.py:60] - Pulling translations for [paragon].
15:38:15 npm ci
15:38:22 npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
15:38:24 
15:38:24 added 1283 packages, and audited 1488 packages in 9s
15:38:24 
15:38:24 159 packages are looking for funding
15:38:24   run `npm fund` for details
15:38:24 
15:38:24 9 vulnerabilities (1 low, 7 high, 1 critical)
15:38:24 
15:38:24 To address issues that do not require attention, run:
15:38:24   npm audit fix
15:38:24 
15:38:24 To address all issues (including breaking changes), run:
15:38:24   npm audit fix --force
15:38:24 
15:38:24 Run `npm audit` for details.
15:38:24 tx pull -t -f --mode reviewed --languages="ar,ca,es_419,fr,he,id,ko_KR,pl,pt_BR,ru,th,uk,zh_CN"
15:38:24 # Getting info about resources
15:38:24 
15:38:24 edx-platform.paragon - Getting info
15:38:34 edx-platform.paragon - Done
15:38:34 
15:38:34 # Pulling files
15:38:34 
15:38:34 edx-platform.paragon [ca] - Pulling file
15:38:34 edx-platform.paragon [ar] - Pulling file
15:38:34 edx-platform.paragon [es_419] - Pulling file
15:38:34 edx-platform.paragon [he] - Pulling file
15:38:34 edx-platform.paragon [fr] - Pulling file
15:38:34 edx-platform.paragon [ar] - Creating download job
15:38:34 edx-platform.paragon [he] - Creating download job
15:38:34 edx-platform.paragon [es_419] - Creating download job
15:38:34 edx-platform.paragon [fr] - Creating download job
15:38:34 edx-platform.paragon [ca] - Creating download job
15:38:36 edx-platform.paragon [ca] - Done
15:38:36 edx-platform.paragon [id] - Pulling file
15:38:36 edx-platform.paragon [id] - Creating download job
15:38:36 edx-platform.paragon [he] - Done
15:38:36 edx-platform.paragon [ko_KR] - Pulling file
15:38:36 edx-platform.paragon [ko_KR] - Creating download job
15:38:36 edx-platform.paragon [fr] - Done
15:38:36 edx-platform.paragon [pl] - Pulling file
15:38:36 edx-platform.paragon [pl] - Creating download job
15:38:36 edx-platform.paragon [es_419] - Done
15:38:36 edx-platform.paragon [pt_BR] - Pulling file
15:38:36 edx-platform.paragon [pt_BR] - Creating download job
15:38:37 edx-platform.paragon [ar] - Done
15:38:37 edx-platform.paragon [ru] - Pulling file
15:38:37 edx-platform.paragon [ru] - Creating download job
15:38:39 edx-platform.paragon [ru] - Done
15:38:39 edx-platform.paragon [th] - Pulling file
15:38:39 edx-platform.paragon [th] - Creating download job
15:38:39 edx-platform.paragon [pt_BR] - Done
15:38:39 edx-platform.paragon [uk] - Pulling file
15:38:39 edx-platform.paragon [uk] - Creating download job
15:38:40 edx-platform.paragon [id] - Done
15:38:40 edx-platform.paragon [zh_CN] - Pulling file
15:38:40 edx-platform.paragon [zh_CN] - Creating download job
15:38:40 edx-platform.paragon [th] - Done
15:38:41 edx-platform.paragon [uk] - Done
15:38:42 edx-platform.paragon [zh_CN] - Done
15:38:44 edx-platform.paragon [ko_KR] - Done
15:38:45 edx-platform.paragon [pl] - Done
15:38:45 # compile files with translated strings to KEYVALUEJSON format which react-intl understands...
15:38:45 npm run-script i18n_compile
15:38:45 
15:38:45 > @edx/paragon@20.18.1 i18n_compile
15:38:45 > formatjs compile-folder --format transifex ./src/i18n/messages ./src/i18n/messages
15:38:45 
15:38:45 [@formatjs/cli] [WARN] Error validating message "نوع {count، plural, one {الملف} other {الملفات}} المقبول هو {typeString}." with ID "dropzone.Dropzone.invalidType" in file "./src/i18n/messages/ar.json"
15:38:45 SyntaxError: MALFORMED_ARGUMENT
15:38:45     at parse5 (/edx/var/jenkins/jobs/translations/jobs/paragon-pull_translations/workspace/ecommerce-scripts/paragon/node_modules/@formatjs/cli/bin/formatjs:147987:21)
15:38:45     at compile7 (/edx/var/jenkins/jobs/translations/jobs/paragon-pull_translations/workspace/ecommerce-scripts/paragon/node_modules/@formatjs/cli/bin/formatjs:149647:67)
15:38:45     at async Promise.all (index 0)
15:38:45     at async compileFolder (/edx/var/jenkins/jobs/translations/jobs/paragon-pull_translations/workspace/ecommerce-scripts/paragon/node_modules/@formatjs/cli/bin/formatjs:149707:19)
15:38:45     at async Command.<anonymous> (/edx/var/jenkins/jobs/translations/jobs/paragon-pull_translations/workspace/ecommerce-scripts/paragon/node_modules/@formatjs/cli/bin/formatjs:155032:5)
15:38:45 Makefile:51: recipe for target 'pull_translations' failed
15:38:45 make: *** [pull_translations] Error 1
15:38:46 Traceback (most recent call last):
15:38:46   File "transifex/pull.py", line 120, in <module>
15:38:46     pull(
15:38:46   File "transifex/pull.py", line 62, in pull
15:38:46     repo.pull_translations()
15:38:46   File "/edx/var/jenkins/jobs/translations/jobs/paragon-pull_translations/workspace/ecommerce-scripts/transifex/utils.py", line 192, in pull_translations
15:38:46     subprocess.run(['make', 'pull_translations'], check=True)
15:38:46   File "/usr/lib/python3.8/subprocess.py", line 516, in run
15:38:46     raise CalledProcessError(retcode, process.args,
15:38:46 subprocess.CalledProcessError: Command '['make', 'pull_translations']' returned non-zero exit status 2.
15:38:46 Build step 'Execute shell' marked build as failure
15:38:46 Archiving artifacts
15:38:46 Sending e-mails to: astankiewicz@2u.com
15:38:47 Finished: FAILURE
```

**Comment by adamstankiewicz** [comment]
@adamstankiewicz to touch base with the Translations WG to try to get the invalid translation resolved.

**Comment by adamstankiewicz** [comment]
Discussion thread in the Open edX Translations Working Group Slack workspace: https://openedx.slack.com/archives/C037XDB9KN1/p1674834568160009

**Comment by adamstankiewicz** [comment]
The `pull_translations` job is passing again, for now. I got support to mark those translations as "unreviewed" so they do not get pulled in by the job.

That said, there still is an underlying issue with 2 separate translations for the `ar` locale:
* `dropzone.Dropzone.invalidType`
* `pgn.Dropzone.DefaultContent.fileTypeRestriction`

**Comment by brian-smith-tcril** [comment]
I'm going to close this in favor of the more specific https://github.com/openedx/paragon/issues/1990
